### ISSUE TITLE
Make more parameters adjustable at runtime

### ISSUE THREAD

**Issue by dabch** [stelzch/holoview#7]
This will reduce the need for live code changes and accelerate and simplify the work on holMOS

**Comment by stelzch** [comment]
As of version 0.0.3, the following parameters are accessible:
- brightness
- contrast
- saturation
- resolution
- AWB mode
- AWB gains
- DRC
- ISO
- shutter speed
- exposure mode

I'll close that issue for now, but at some point we'd might like to add a parameter to the list above.
