### ISSUE TITLE
Shouldn't the preview overlay's resolution adapt to the screen size and resolution?

### ISSUE THREAD

**Issue by dabch** [stelzch/holoview#8]
https://github.com/stelzch/holoview/blob/b6a4202b063141972e8b19f822c6e12621ed6dc9/holoview/mainwindow.py#L138

The overlay's size is fixed to 1920x1080p - is there a reason why that doesn't depend on the pi's display's resolution?

**Comment by stelzch** [comment]
The overlay was intended to show a small text with the shortcuts to capture/end preview for usability reasons.
It should get resized to the screen size automagically, however this has not been tested yet.
